---
- hosts: all
  become: yes
  tasks:
  - name: Copy target files to host
    copy:
      src: "{{ playbook_dir }}/target"
      dest: /home/vagrant/
      owner: vagrant
      directory_mode: yes
  - name: Run web
    shell: "sudo java -jar -Dserver.port=8082 spring-petclinic-2.4.2.jar“
      
