---
- hosts: webservers
  tasks:
    - name: deploy jar
      shell: sudo cp /var/lib/jenkins/workspace/web/target/spring-petclinic-2.4.2.jar
    
    - name: run the jar
      shell: java -jar -Dserver.port=8082 spring-petclinic-2.4.2.jar >/dev/null 2>&1 &